import Navbar from '@/components/navbar';
import './globals.css';
import { Inter } from 'next/font/google';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en'>
      <body suppressHydrationWarning={true} className={inter.className}>
        <Navbar />
        {children}
      </body>
    </html>
  );
}

export async function getServerSideProps(context: any) {
  console.log('CHECK');
  // Fetch data from an API
  const res = await fetch('https://example.com/data');
  // const data = await res.json();
  const data = '';

  console.log('DATA', data);
  // Pass data to the page via props
  return {
    props: {
      data,
    },
  };
}
